project:
  type: website
  output-dir: docsAAA

website:
  title: "Mehadi Hasan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - interest.qmd

format:
  html:
    theme: standstone
    mainfont: ariel
    css: styles.css
    toc: true
    fontcolor: "#0394fc"

editor: visual

