project:
  type: website
  output-dir: docs

website:
  title: "Mehadi Hasan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - tutorials.qmd
      - dataset.qmd
      - myblog.qmd
      - interest.qmd
      - faq.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    mainfont: ariel
    fontcolor: "#121412"
    linkcolor: "#073ee3"
    fontsize: 1.5em
    monofont: courier new

editor: visual

