project:
  type: website
  output-dir: docs

website:
  title: "Mehadi Hasan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - interest.qmd

format:
  html:
    theme: standstone
    css: styles.css
    toc: true
    mainfont: ariel
    fontcolor: "#121412"
    linkcolor: "#073ee3"
    fontsize: 1.5em
    monofont: courier new

editor: visual

